// <auto-generated />
using System;
using Challenge_PM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace PM_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge_PM.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ALERTA");

                    b.Property<int?>("SensorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Sensor_Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FK_ID_SENSOR");

                    b.Property<int?>("TipoAlertaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo_Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FK_ID_FUNCIONARIO");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("TipoAlertaId");

                    b.ToTable("T_NET_ALERTA", (string)null);
                });

            modelBuilder.Entity("Challenge_PM.Models.DataCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DATACENTER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SETOR");

                    b.Property<string>("StatusDatacenter")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS_DATACENTER");

                    b.HasKey("Id");

                    b.ToTable("T_NET_DATACENTER", (string)null);
                });

            modelBuilder.Entity("Challenge_PM.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FUNCIONARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoFuncionario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CARGO_FUNCIONARIO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL_FUNCIONARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_FUNCIONARIO");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TEL_FUNCIONARIO");

                    b.HasKey("Id");

                    b.ToTable("T_NET_FUNCIONARIO", (string)null);
                });

            modelBuilder.Entity("Challenge_PM.Models.Manutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MANUTENCAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Alerta_Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FK_ID_ALERTA");

                    b.Property<DateTime>("DataManutencao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_MANUTENCAO");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Funcionario_Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FK_ID_FUNCIONARIO");

                    b.Property<string>("StatusManutencao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS_MANUTENCAO");

                    b.Property<string>("TipoManutencao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO_MANUTENCAO");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("T_NET_MANUTENCAO", (string)null);
                });

            modelBuilder.Entity("Challenge_PM.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtividadeSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ATIVIDADE_SENSOR");

                    b.Property<int?>("DataCenterId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DataCenter_Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FK_ID_DATACENTER");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO_SENSOR");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.HasKey("Id");

                    b.HasIndex("DataCenterId");

                    b.ToTable("T_NET_SENSOR", (string)null);
                });

            modelBuilder.Entity("Challenge_PM.Models.TipoAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nivel_alerta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NIVEL_ALERTA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("T_NET_TIPO_ALERTA", (string)null);
                });

            modelBuilder.Entity("Challenge_PM.Models.Alerta", b =>
                {
                    b.HasOne("Challenge_PM.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId");

                    b.HasOne("Challenge_PM.Models.TipoAlerta", "TipoAlerta")
                        .WithMany()
                        .HasForeignKey("TipoAlertaId");

                    b.Navigation("Sensor");

                    b.Navigation("TipoAlerta");
                });

            modelBuilder.Entity("Challenge_PM.Models.Manutencao", b =>
                {
                    b.HasOne("Challenge_PM.Models.Alerta", "Alerta")
                        .WithMany()
                        .HasForeignKey("AlertaId");

                    b.HasOne("Challenge_PM.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Alerta");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Challenge_PM.Models.Sensor", b =>
                {
                    b.HasOne("Challenge_PM.Models.DataCenter", "DataCenter")
                        .WithMany()
                        .HasForeignKey("DataCenterId");

                    b.Navigation("DataCenter");
                });
#pragma warning restore 612, 618
        }
    }
}
